import type { Metadata } from "next";
// Next.js 中的Metadata​是用于管理网页元数据的核心机制，
// 它通过声明式配置或文件约定，自动生成 HTML 的 <head> 标签内容，优化 SEO 和用户体验
import "./globals.css";
import '@rainbow-me/rainbowkit/styles.css'; // RainbowKit 需要全局 CSS 样式才能正确显示
import Provider from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
